import {
  Activity,
  AlarmCheck,
  Album,
  Anvil,
  Aperture,
  Archive,
  Award,
  Axe,
  Baby,
  Backpack,
  BadgeCheck,
  Banknote,
  Battery,
  BatteryCharging,
  Beaker,
  Bell,
  BellRing,
  Bird,
  Blinds,
  Bone,
  Book,
  BookImage,
  Bookmark,
  BookOpen,
  Box,
  Boxes,
  Bug,
  Building,
  Cake,
  Calculator,
  Calendar,
  Camera,
  Car,
  CassetteTape,
  Cast,
  Cat,
  Cctv,
  ChefHat,
  Circle,
  Citrus,
  Clipboard,
  ClipboardList,
  Clock,
  Cloud,
  CloudRain,
  CloudSnow,
  Coffee,
  Coins,
  Computer,
  Container,
  CookingPot,
  Cpu,
  CreditCard,
  Cross,
  Cuboid,
  Cylinder,
  Dice6,
  Disc,
  Disc2,
  Dog,
  Dribbble as Basketball,
  Drill,
  Droplet,
  Dumbbell,
  Ear,
  Edit2 as Pen,
  Egg,
  Eye,
  Feather,
  Fence,
  File,
  FileImage,
  Film,
  Fingerprint,
  Fish,
  Flag,
  Flame,
  FlagTriangleRight,
  Flashlight,
  FlaskRound as Flask,
  Flower,
  Flower2,
  Folder,
  FolderOpen,
  Frown,
  Gavel,
  Gem,
  Glasses,
  Globe,
  GraduationCap,
  Hammer,
  Hand,
  HandMetal,
  HardDrive,
  HardHat,
  HeartPulse,
  Hexagon,
  Highlighter,
  Image,
  Inbox,
  Joystick,
  Key,
  KeyboardMusic,
  KeyRound,
  Lamp,
  LampFloor,
  Landmark as Bank,
  Laptop,
  Layers,
  Leaf,
  LeafyGreen,
  LibraryBig as Library,
  Lightbulb,
  Lock,
  Magnet,
  Mailbox,
  Map,
  Megaphone,
  MessageCircle,
  Mic2,
  Microwave,
  Monitor,
  Moon,
  MoonStar,
  Mouse,
  Navigation,
  Notebook,
  NotebookPen,
  Octagon,
  Origami,
  Package,
  Package2,
  PackageOpen,
  PaintBucket,
  Palette,
  Paperclip,
  PawPrint,
  PencilRuler,
  PenTool,
  Phone,
  Piano,
  PiggyBank,
  Pill,
  PillBottle,
  Pin,
  Plane,
  Play,
  PlayCircle,
  Plug,
  Pocket,
  Presentation,
  Printer,
  Puzzle,
  RadioTower,
  Rainbow,
  Receipt,
  RectangleGoggles,
  RectangleVertical,
  RectangleHorizontal,
  Refrigerator,
  Ribbon,
  Rocket,
  RockingChair,
  Router,
  Ruler,
  RulerDimensionLine,
  Sailboat,
  Save,
  School,
  Scissors,
  Search,
  Send,
  Server,
  Shell,
  Shield,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Shovel,
  ShowerHead,
  Shredder,
  SignpostBig,
  Slice,
  Smartphone,
  Smile,
  Speaker,
  SprayCan,
  Sprout,
  Square,
  SquareScissors,
  Squirrel,
  Stamp,
  Star,
  Store,
  Sun,
  SwatchBook,
  Sword,
  Syringe,
  Tablet,
  Tag,
  Target,
  Telescope,
  Theater,
  Thermometer,
  ToyBrick,
  Trash,
  Trash2,
  TreePalm as PalmTree,
  TreePine as PineTree,
  Trees,
  Triangle,
  Trophy,
  Tv,
  User,
  Users,
  Utensils,
  UtensilsCrossed,
  Vault,
  Video,
  Volleyball,
  WalletCards,
  WandSparkles,
  Warehouse,
  WashingMachine,
  Watch,
  WavesLadder,
  Webcam,
  Wifi,
  Wrench,
  Zap as Lightning,
} from "lucide-react";

import {
  Armchair,
  AtSign,
  Bed,
  Beer,
  Bike,
  Binoculars,
  Briefcase,
  BriefcaseBusiness,
  Brush,
  BrushCleaning,
  BoomBox,
  Burger,
  Cable,
  Chess,
  ChessQueen,
  DressForm,
  Drum,
  Fabric,
  FabricFolded,
  FireExtinguisher,
  Football,
  Fuel,
  Gamepad,
  Gamepad2,
  Ghost,
  Gift,
  GlassWater,
  Glue,
  Guitar,
  Handbag,
  Headphones,
  Horse,
  House,
  Kayak,
  Keyboard,
  Knife,
  Lawnmower,
  LifeBuoy,
  Luggage,
  Mail,
  MapPin,
  MemoryStick,
  Mic,
  Microscope,
  Music,
  Music2,
  Nails,
  Paintbrush,
  PaintRoller,
  PinCushion,
  Pocketknife,
  Projector,
  Rake,
  SewingMachine,
  SoccerBall,
  Sofa,
  Spool,
  Stethoscope,
  Tent,
  Thread,
  Tractor,
  Trailer,
  Tram,
  Truck,
  Turntable,
  Turtle,
  Umbrella,
  Videotape,
  Wallet,
  Wine,
  WineBottle,
} from "@/app/assets";

export const lucideIconList = {
  Activity: {
    Component: Activity,
    tags: ["Heartbeat", "Pulse", "Health", "Test"],
  },
  AlarmCheck: {
    Component: AlarmCheck,
    tags: ["Clock", "Reminder", "Stopwatch", "Time", "Todo"],
  },
  Album: { Component: Album, tags: ["Pictures", "Photos", "Memories"] },
  Anvil: { Component: Anvil, tags: ["Metal", "Iron", "Smith", "Shape"] },
  Aperture: {
    Component: Aperture,
    tags: ["Camera", "Lens", "Photography", "Pictures", "Image", "Art"],
  },
  Box: { Component: Archive, tags: ["Archive", "Container", "Files"] },
  Armchair: {
    Component: Armchair,
    tags: [
      "Sofa",
      "Loveseat",
      "Chair",
      "Furniture",
      "Living room",
      "Den",
      "Home",
      "Couch",
      "Rest",
    ],
  },
  AtSign: { Component: AtSign, tags: ["Social", "Email", "Notify"] },
  Award: { Component: Award, tags: [] },
  Axe: { Component: Axe, tags: [] },
  Baby: { Component: Baby, tags: ["Child", "Infant", "Kid", "Family"] },
  Backpack: {
    Component: Backpack,
    tags: [
      "Luggage",
      "Bag",
      "School",
      "Storage",
      "Portable",
      "Hiking",
      "Carry",
    ],
  },
  BadgeCheck: { Component: BadgeCheck, tags: [] },
  Money: {
    Component: Banknote,
    tags: [
      "Banknote",
      "Dollar",
      "Cash",
      "Savings",
      "Finance",
      "Investment",
      "Payment",
    ],
  },
  Basketball: {
    Component: Basketball,
    tags: ["Sports", "Sporting goods", "Equipment"],
  },
  Battery: { Component: Battery, tags: ["Electricity", "Charger"] },
  BatteryCharging: { Component: BatteryCharging, tags: [] },
  Beaker: { Component: Beaker, tags: ["Science", "Mixing", "Chemistry"] },
  Bed: { Component: Bed, tags: ["Sleep", "Home", "Room", "Rest", "Furniture"] },
  Beer: { Component: Beer, tags: ["Drink", "Alcohol", "Brew", "Bar", "Pub"] },
  Bell: { Component: Bell, tags: ["Ring", "Reminder", "Alert"] },
  BellRing: { Component: BellRing, tags: [] },
  Bike: {
    Component: Bike,
    tags: [
      "Bicyle",
      "Cycling",
      "Sports",
      "Transportation",
      "Wheels",
      "Motorcycle",
    ],
  },
  Binoculars: { Component: Binoculars, tags: [] },
  Bird: { Component: Bird, tags: ["Pet", "Animal", "Feathers"] },
  Blinds: {
    Component: Blinds,
    tags: ["Curtains", "Home", "Shade", "Window", "Decor"],
  },
  Bone: { Component: Bone, tags: ["Dog", "Treat", "Skeleton"] },
  Book: { Component: Book, tags: ["Library", "Education", "Reading"] },
  BookImage: {
    Component: BookImage,
    tags: ["Photobook", "Pictures", "Album", "Memories", "Family"],
  },
  Bookmark: { Component: Bookmark, tags: [] },
  BookOpen: {
    Component: BookOpen,
    tags: ["Reading", "Learning", "Study", "Library"],
  },
  BoomBox: {
    Component: BoomBox,
    tags: ["Speaker", "Music", "Sound", "Radio", "Loud"],
  },
  Box: { Component: Box, tags: ["Container", "Storage"] },
  Boxes: { Component: Boxes, tags: ["Containers", "Storage"] },
  Briefcase: {
    Component: Briefcase,
    tags: ["Luggage", "Business", "Bag", "Suitcase"],
  },
  BriefcaseBusiness: {
    Component: BriefcaseBusiness,
    tags: ["Luggage", "Bag", "Attache", "Suitcase"],
  },
  Brush: { Component: Brush, tags: ["Paint", "Color"] },
  BrushCleaning: {
    Component: BrushCleaning,
    tags: ["Sweep", "Broom", "Clean", "Dirt", "Mop", "Floor"],
  },
  Bug: { Component: Bug, tags: ["Insect", "Pest"] },
  Building: { Component: Building, tags: [] },
  Burger: {
    Component: Burger,
    tags: ["Food", "Hamburger", "Cheeseburger", "Kitchen"],
  },
  Cable: { Component: Cable, tags: [] },
  Cake: {
    Component: Cake,
    tags: ["Food", "Dessert", "Birthday", "Sweets", "Pastry", "Baking"],
  },
  Calculator: {
    Component: Calculator,
    tags: ["Math", "Numbers", "Add", "Subtract", "Multiply", "Divide"],
  },
  Calendar: { Component: Calendar, tags: [] },
  Camera: {
    Component: Camera,
    tags: ["Photography", "Pictures", "Lens", "Capture"],
  },
  Car: {
    Component: Car,
    tags: ["Vehicle", "Travel", "Transportation", "SUV", "Wheels", "Commute"],
  },
  CassetteTape: {
    Component: CassetteTape,
    tags: ["Retro", "Music", "Sound", "Tape", "Recording"],
  },
  Cast: {
    Component: Cast,
    tags: [
      "Wifi",
      "Internet",
      "Chromecast",
      "TV",
      "Watch",
      "Entertainment",
      "Media",
    ],
  },
  Cat: { Component: Cat, tags: ["Pet", "Feline", "Home", "Cute", "Kitten"] },
  Cctv: { Component: Cctv, tags: ["Video", "Home security", "Surveillance"] },
  ChefHat: {
    Component: ChefHat,
    tags: ["Cooking", "Kitchen", "Restaurant", "Dining", "Home", "Food"],
  },
  Chess: {
    Component: Chess,
    tags: ["Pawn", "Games", "Board games"],
  },
  ChessQueen: {
    Component: ChessQueen,
    tags: ["Queen", "Games", "Board games"],
  },
  Circle: { Component: Circle, tags: ["Shapes", "Round"] },
  Citrus: { Component: Citrus, tags: ["Lemon", "Lime", "Fruit", "Healthy"] },
  Clipboard: { Component: Clipboard, tags: ["Petition", "Todo", "List"] },
  ClipboardList: { Component: ClipboardList, tags: ["Todo", "To-do"] },
  Clock: { Component: Clock, tags: ["Time"] },
  Cloud: { Component: Cloud, tags: ["Weather", "Sky"] },
  CloudRain: {
    Component: CloudRain,
    tags: ["Weather", "Sky", "Thunder", "Rain", "Storm"],
  },
  CloudSnow: {
    Component: CloudSnow,
    tags: ["Weather", "Sky", "Cold", "Winter"],
  },
  Coffee: {
    Component: Coffee,
    tags: ["Brew", "Caffeine", "Awake", "Alert", "Java", "Joe", "Cafe"],
  },
  Coins: { Component: Coins, tags: ["Money", "Change", "Quarter"] },
  Computer: {
    Component: Computer,
    tags: ["Electronics", "Desktop", "Technology", "Devices", "Laptop"],
  },
  Container: { Component: Container, tags: ["Box", "Storage"] },
  CookingPot: { Component: CookingPot, tags: ["Pans", "Kitchen", "Food"] },
  Cpu: {
    Component: Cpu,
    tags: ["Computer", "Chip", "Electronics", "Motherboard", "Processor"],
  },
  CreditCard: {
    Component: CreditCard,
    tags: ["Plastic", "Payment", "Money", "Finance"],
  },
  Cross: { Component: Cross, tags: ["Plus", "Add"] },
  Cuboid: { Component: Cuboid, tags: ["Shapes"] },
  Cylinder: { Component: Cylinder, tags: ["Shapes"] },
  Dice: {
    Component: Dice6,
    tags: ["Games", "Gaming", "Gambling", "Board games", "Betting"],
  },
  Disc: {
    Component: Disc,
    tags: [
      "CD",
      "Music",
      "Tape",
      "Audio",
      "DVD",
      "Movie",
      "Recording",
      "Digital",
      "Entertainment",
    ],
  },
  Disc2: {
    Component: Disc2,
    tags: [
      "CD",
      "Music",
      "Tape",
      "Audio",
      "DVD",
      "Movie",
      "Recording",
      "Digital",
      "Entertainment",
    ],
  },
  Dog: { Component: Dog, tags: ["Pet", "Animal", "Family"] },
  DressForm: {
    Component: DressForm,
    tags: ["Sewing", "Crafts", "Clothing", "Fabric"],
  },
  Drill: {
    Component: Drill,
    tags: ["Tools", "Home", "Wood", "Hole", "Screw", "Power tools"],
  },
  Droplet: {
    Component: Droplet,
    tags: ["Water", "Liquid", "Ocean", "Hydrate"],
  },
  Drum: {
    Component: Drum,
    tags: ["Snare", "Musical", "Instruments", "Sound", "Percussion", "Beat"],
  },
  Dumbbell: {
    Component: Dumbbell,
    tags: ["Exercise", "Gym", "Weights", "Lifting", "Iron"],
  },
  Ear: { Component: Ear, tags: ["Hearing", "Sound"] },
  Egg: { Component: Egg, tags: ["Cooking", "Food", "Kitchen"] },
  Eye: { Component: Eye, tags: ["Vision", "Sight", "See"] },
  Fabric: { Component: Fabric, tags: ["Cloth", "Bolt", "Sewing", "Crafts"] },
  FabricFolded: {
    Component: FabricFolded,
    tags: ["Cloth", "Bolt", "Sewing", "Crafts"],
  },
  Feather: { Component: Feather, tags: [] },
  Fence: {
    Component: Fence,
    tags: ["Yard", "Boundary", "Picket", "Gate", "Private"],
  },
  File: { Component: File, tags: [] },
  FileImage: { Component: FileImage, tags: [] },
  Film: { Component: Film, tags: ["Photography", "Movies", "Camera"] },
  Fingerprint: { Component: Fingerprint, tags: [] },
  FireExtinguisher: {
    Component: FireExtinguisher,
    tags: ["Safety", "Protection", "Flame"],
  },
  Fish: {
    Component: Fish,
    tags: ["Ocean", "Sea", "Food", "Animals", "Bass", "Trout"],
  },
  Flag: { Component: Flag, tags: [] },
  Flame: {
    Component: Flame,
    tags: ["Fire", "Hot", "Heat", "Camping", "Danger"],
  },
  FlagTriangleRight: { Component: FlagTriangleRight, tags: [] },
  Flashlight: {
    Component: Flashlight,
    tags: ["Torch", "Illuminate", "Bright", "EDC"],
  },
  Flask: {
    Component: Flask,
    tags: ["Science", "Chemistry", "Mix", "Chemicals"],
  },
  Flower: {
    Component: Flower,
    tags: ["Bloom", "Plants", "Garden", "Pretty", "Bouquet"],
  },
  Flower2: {
    Component: Flower2,
    tags: ["Bloom", "Plants", "Garden", "Pretty", "Bouquet"],
  },
  Folder: { Component: Folder, tags: ["Files", "Storage"] },
  FolderOpen: { Component: FolderOpen, tags: [] },
  Football: { Component: Football, tags: ["Sporting good", "Balls", "Sports"] },
  Frown: {
    Component: Frown,
    tags: ["Sad", "Unhappy", "Bad", "Displeased", "Expression"],
  },
  Fuel: { Component: Fuel, tags: ["Power", "Oil", "Gasoline", "Pump"] },
  Gamepad: {
    Component: Gamepad,
    tags: [
      "Gaming",
      "Play",
      "Entertainment",
      "Joystick",
      "Playstation",
      "Nintendo",
      "XBox",
      "RPG",
    ],
  },
  Gamepad2: {
    Component: Gamepad2,
    tags: [
      "Gaming",
      "Play",
      "Entertainment",
      "Joystick",
      "Playstation",
      "Nintendo",
      "XBox",
      "RPG",
    ],
  },
  Gavel: {
    Component: Gavel,
    tags: [
      "Judge",
      "Court",
      "Hammer",
      "Justice",
      "Law",
      "Legal",
      "Decision",
      "Mallet",
    ],
  },
  Gem: {
    Component: Gem,
    tags: [
      "Diamond",
      "Jewelry",
      "Crafts",
      "Ring",
      "Valuables",
      "Expensive",
      "Ruby",
      "Emerald",
    ],
  },
  Ghost: { Component: Ghost, tags: ["Spooky", "Halloween", "Costume"] },
  Gift: { Component: Gift, tags: ["Present", "Bow", "Christmas"] },
  Glasses: { Component: Glasses, tags: ["Vision", "Eyes", "Sight"] },
  GlassWater: { Component: GlassWater, tags: ["Drinks", "Liquid", "Dishes"] },
  Globe: {
    Component: Globe,
    tags: ["Round", "Earth", "World", "Map", "Navigation", "Atlas"],
  },
  Glue: {
    Component: Glue,
    tags: ["Crafts", "Sewing", "Sticky", "Adhesive", "Leather"],
  },
  GraduationCap: {
    Component: GraduationCap,
    tags: ["School", "College", "University", "Education", "Diploma"],
  },
  Guitar: {
    Component: Guitar,
    tags: ["Music", "Instruments", "Strings", "Band"],
  },
  Hammer: {
    Component: Hammer,
    tags: ["Nails", "Tools", "Repair", "Woodworking", "Carpentry"],
  },
  Hand: { Component: Hand, tags: [] },
  Handbag: { Component: Handbag, tags: ["Purse", "Bag"] },
  HandMetal: { Component: HandMetal, tags: [] },
  HardDrive: {
    Component: HardDrive,
    tags: ["Storage", "Memory", "Electronics", "Computer", "Disk", "Files"],
  },
  HardHat: {
    Component: HardHat,
    tags: ["Construction", "Build", "Make", "Safety", "Protection", "Headgear"],
  },
  Headphones: {
    Component: Headphones,
    tags: ["Music", "Earphones", "Play", "Sound", "Hearing"],
  },
  HeartPulse: {
    Component: HeartPulse,
    tags: ["Health", "Activity", "Beat", "Testing"],
  },
  Hexagon: { Component: Hexagon, tags: ["Shapes"] },
  Highlighter: {
    Component: Highlighter,
    tags: ["Neon", "Drawing", "Color", "Crafts"],
  },
  Home: { Component: House, tags: ["House", "Family"] },
  Horse: {
    Component: Horse,
    tags: ["Animals", "Equestrian", "Farm", "Riding"],
  },
  Image: { Component: Image, tags: ["Picture", "Photo", "Memories"] },
  Inbox: { Component: Inbox, tags: ["Mail", "Notification", "Letters"] },
  Joystick: {
    Component: Joystick,
    tags: [
      "Game",
      "Play",
      "Electronics",
      "Gaming",
      "Atari",
      "Nintendo",
      "Playstation",
      "XBox",
      "Controller",
    ],
  },
  Kayak: {
    Component: Kayak,
    tags: [
      "Canoe",
      "Outdoors",
      "Sporting goods",
      "Camping",
      "Rafting",
      "Water",
      "Lake",
    ],
  },
  Key: { Component: Key, tags: ["Security", "Safety", "Door", "Home"] },
  KeyRound: {
    Component: KeyRound,
    tags: ["Security", "Safety", "Door", "Home"],
  },
  Keyboard: { Component: Keyboard, tags: ["Typing", "Computer"] },
  KeyboardMusic: {
    Component: KeyboardMusic,
    tags: ["Piano", "Instruments", "Synthesizer"],
  },
  Knife: { Component: Knife, tags: ["Kitchen", "Cut", "Sharp", "Chef"] },
  Lamp: { Component: Lamp, tags: ["Light", "Bulb", "Home", "Decor"] },
  LampFloor: { Component: LampFloor, tags: ["Light", "Bulb", "Home", "Decor"] },
  Bank: {
    Component: Bank,
    tags: ["Landmark", "Building", "Institution", "Monument"],
  },
  Laptop: {
    Component: Laptop,
    tags: ["Computer", "Electronics", "Desktop", "Gear", "Gaming"],
  },
  Lawnmower: {
    Component: Lawnmower,
    tags: ["Yard work", "Grass", "Outdoors", "Tools"],
  },
  Layers: { Component: Layers, tags: [] },
  Leaf: { Component: Leaf, tags: [] },
  LeafyGreen: { Component: LeafyGreen, tags: [] },
  Library: { Component: Library, tags: ["Books", "Reading", "Collection"] },
  LifeBuoy: {
    Component: LifeBuoy,
    tags: ["Water", "Rescue", "Safety", "Flotation", "Floatation", "Swimming"],
  },
  Lightbulb: { Component: Lightbulb, tags: ["Idea", "Light", "Home"] },
  Lightning: {
    Component: Lightning,
    tags: [
      "Storm",
      "Weather",
      "Idea",
      "Thunder",
      "Bolt",
      "Danger",
      "Electricity",
    ],
  },
  Lock: { Component: Lock, tags: ["Security", "Key", "Safety"] },
  Luggage: {
    Component: Luggage,
    tags: ["Travel", "Storage", "Clothes", "Bags"],
  },
  Magnet: { Component: Magnet, tags: ["Attract", "Attach"] },
  Mail: { Component: Mail, tags: [] },
  Mailbox: { Component: Mailbox, tags: [] },
  Map: { Component: Map, tags: ["Atlas", "Navigation", "Route", "Plan"] },
  MapPin: {
    Component: MapPin,
    tags: ["Locations", "GPS", "Directions", "Landmark", "Site", "Navigation"],
  },
  Megaphone: { Component: Megaphone, tags: [] },
  MemoryStick: {
    Component: MemoryStick,
    tags: ["USB", "Thumb drive", "Disk", "Storage", "Computers", "Files"],
  },
  Message: {
    Component: MessageCircle,
    tags: ["Text", "Communication", "Talk", "Chat"],
  },
  Mic: {
    Component: Mic,
    tags: ["Podcast", "Sound", "Radio", "Electronics", "Recording"],
  },
  Mic2: {
    Component: Mic2,
    tags: ["Podcast", "Sound", "Radio", "Electronics", "Recording"],
  },
  Microscope: { Component: Microscope, tags: ["Science", "Magnify", "Slides"] },
  Microwave: {
    Component: Microwave,
    tags: ["Kitchen", "Appliances", "Cook", "Nuke", "Food"],
  },
  Monitor: {
    Component: Monitor,
    tags: ["Computer", "Electronics", "Devices", "Accessories", "Peripherals"],
  },
  Moon: { Component: Moon, tags: ["Sky", "Night"] },
  MoonStar: { Component: MoonStar, tags: ["Sky", "Night"] },
  Mouse: {
    Component: Mouse,
    tags: ["Computer", "Electronics", "Devices", "Accessories", "Peripherals"],
  },
  Music: {
    Component: Music,
    tags: ["Notes", "Sheet", "Sound", "Instruments", "Orchestra"],
  },
  Music2: {
    Component: Music2,
    tags: ["Notes", "Sheet", "Sound", "Instruments", "Orchestra"],
  },
  Nails: { Component: Nails, tags: [] },
  Navigation: {
    Component: Navigation,
    tags: ["GPS", "Route", "Directions", "Location"],
  },
  Notebook: { Component: Notebook, tags: [] },
  NotebookPen: { Component: NotebookPen, tags: [] },
  Octagon: { Component: Octagon, tags: ["Shapes", "Stop sign"] },
  Origami: { Component: Origami, tags: ["Crafts", "Swan"] },
  Package: { Component: Package, tags: [] },
  Package2: { Component: Package2, tags: [] },
  PackageOpen: { Component: PackageOpen, tags: [] },
  Paintbrush: {
    Component: Paintbrush,
    tags: ["Brush", "Color", "Home", "Decor"],
  },
  PaintBucket: {
    Component: PaintBucket,
    tags: ["Brush", "Color", "Home", "Decor"],
  },
  PaintRoller: {
    Component: PaintRoller,
    tags: ["Brush", "Color", "Home", "Decor"],
  },
  Palette: { Component: Palette, tags: ["Brush", "Color", "Home", "Decor"] },
  PalmTree: {
    Component: PalmTree,
    tags: ["Outdoors", "Tropical", "Green", "Plants", "Vacation"],
  },
  Paperclip: { Component: Paperclip, tags: ["Attach", "Staple"] },
  PawPrint: { Component: PawPrint, tags: ["Dog", "Pet", "Foot", "Animal"] },
  Pen: { Component: Pen, tags: ["Writing", "Notes", ""] },
  PencilRuler: { Component: PencilRuler, tags: [] },
  PenTool: { Component: PenTool, tags: [] },
  Phone: {
    Component: Phone,
    tags: ["Dial", "Telephone", "Contact", "Talk", "Speak"],
  },
  Piano: {
    Component: Piano,
    tags: ["Music", "Instruments", "Keyboard", "Sound"],
  },
  PiggyBank: {
    Component: PiggyBank,
    tags: ["Money", "Finance", "Savings", "Cash"],
  },
  Pill: {
    Component: Pill,
    tags: [
      "Medicine",
      "Medication",
      "Pain",
      "Prescription",
      "Headache",
      "Sore",
    ],
  },
  PillBottle: {
    Component: PillBottle,
    tags: [
      "Medicine",
      "Medication",
      "Pain",
      "Prescription",
      "Headache",
      "Sore",
    ],
  },
  Pin: { Component: Pin, tags: ["Thumbtack", "Attach", "Crafts"] },
  PinCushion: { Component: PinCushion, tags: ["Sewing", "Needles", "Crafts"] },
  PineTree: {
    Component: PineTree,
    tags: ["Green", "Outdoors", "Plant", "Woods"],
  },
  Plane: {
    Component: Plane,
    tags: ["Jet", "Travel", "Air", "Aero", "Aviation", "Machines", "Flight"],
  },
  Play: { Component: Play, tags: [] },
  PlayCircle: { Component: PlayCircle, tags: [] },
  Plug: { Component: Plug, tags: ["Electronics", "Power"] },
  Pocket: {
    Component: Pocket,
    tags: ["Storage", "Carry", "Clothes", "Container", "Carry"],
  },
  PocketKnife: {
    Component: Pocketknife,
    tags: ["Cut", "Blade", "EDC", "Tools"],
  },
  Presentation: { Component: Presentation, tags: [] },
  Printer: {
    Component: Printer,
    tags: [
      "Devices",
      "Paper",
      "Accessories",
      "Computer",
      "Electronics",
      "Device",
    ],
  },
  Projector: {
    Component: Projector,
    tags: ["Entertainment", "Movies", "TV", "Home", "Watch"],
  },
  Puzzle: { Component: Puzzle, tags: ["Piece", "Toy", "Games", "Jigsaw"] },
  RadioTower: { Component: RadioTower, tags: [] },
  Rainbow: {
    Component: Rainbow,
    tags: ["Colorful", "Sky", "Weather", "Storm"],
  },
  Rake: { Component: Rake, tags: ["Yardwork", "Tools", "Gardening"] },
  Receipt: {
    Component: Receipt,
    tags: ["Purchase", "Payment", "Record", "Money"],
  },
  RectangleGoggles: {
    Component: RectangleGoggles,
    tags: ["Eye protection", "Ski", "Face"],
  },
  RectangleVertical: { Component: RectangleVertical, tags: ["Shapes"] },
  RectangleHorizontal: { Component: RectangleHorizontal, tags: ["Shapes"] },
  Refrigerator: {
    Component: Refrigerator,
    tags: ["Fridge", "Food", "Cold", "Cool", "Kitchen", "Home", "Appliances"],
  },
  Ribbon: { Component: Ribbon, tags: ["Gift", "Award"] },
  Rocket: {
    Component: Rocket,
    tags: ["Launch", "Space", "Sky", "Aerospace", "Flight"],
  },
  RockingChair: {
    Component: RockingChair,
    tags: ["Furniture", "Home", "Relaxation", "Seat", "Porch"],
  },
  Router: {
    Component: Router,
    tags: ["Internet", "Electronics", "WiFi", "Device", "Home"],
  },
  Ruler: { Component: Ruler, tags: ["Measure", "Crafts", "Tools"] },
  RulerDimensionLine: {
    Component: RulerDimensionLine,
    tags: ["Measure", "Crafts", "Tools"],
  },
  Sailboat: {
    Component: Sailboat,
    tags: ["Watercraft", "Ocean", "Water", "Lake", "Sea"],
  },
  Save: { Component: Save, tags: [] },
  School: { Component: School, tags: ["Education", "Class", "Learning"] },
  Scissors: {
    Component: Scissors,
    tags: ["Cut", "Sewing", "Crafts", "Tools"],
  },
  Search: { Component: Search, tags: ["Find", "Magnifying glass"] },
  Send: { Component: Send, tags: [] },
  Server: {
    Component: Server,
    tags: ["Electronics", "Computers", "Storage", "Internet"],
  },
  SewingMachine: {
    Component: SewingMachine,
    tags: ["Thread", "Clothes", "Crafts", "Garments"],
  },
  Shell: { Component: Shell, tags: [] },
  Shield: { Component: Shield, tags: ["Protection", "Safety"] },
  Shirt: {
    Component: Shirt,
    tags: ["Clothes", "Apparel", "Home", "Wear", "Fashion", "Sewing"],
  },
  ShoppingBag: {
    Component: ShoppingBag,
    tags: ["Store", "Purchase", "Spending"],
  },
  ShoppingCart: {
    Component: ShoppingCart,
    tags: ["Food", "Store", "Purchase", "Spending"],
  },
  Shovel: {
    Component: Shovel,
    tags: ["Tools", "Construction", "Yard", "Dig", "Hole"],
  },
  ShowerHead: {
    Component: ShowerHead,
    tags: [
      "Bathroom",
      "Water",
      "Clean",
      "Home",
      "Toiletries",
      "Soap",
      "Restroom",
    ],
  },
  Shredder: {
    Component: Shredder,
    tags: ["Documents", "Security", "Appliances"],
  },
  SignpostBig: { Component: SignpostBig, tags: [] },
  Razor: { Component: Slice, tags: ["Slice", "Cutter", "Knife", "Crafts"] },
  Smartphone: {
    Component: Smartphone,
    tags: ["Phone", "Device", "iPhone", "Android", "Call", "Electronics"],
  },
  Smile: { Component: Smile, tags: ["Happy", "Face"] },
  SoccerBall: {
    Component: SoccerBall,
    tags: ["Sports", "Sporting goods", "Football"],
  },
  Sofa: {
    Component: Sofa,
    tags: ["Couch", "Home", "Chair", "Rest", "Living room", "Den", "Loveseat"],
  },
  Speaker: {
    Component: Speaker,
    tags: ["Sound", "Music", "Electronics", "Home", "Entertainment"],
  },
  Spool: { Component: Spool, tags: ["Sewing", "Thread", "Yarn", "Crafts"] },
  SprayCan: {
    Component: SprayCan,
    tags: ["Paint", "Graffiti", "Tagging", "Color"],
  },
  Sprout: {
    Component: Sprout,
    tags: ["Garden", "Plants", "Food", "Outdoors", "Outside", "Green"],
  },
  Square: { Component: Square, tags: ["Shapes"] },
  SquareScissors: { Component: SquareScissors, tags: [] },
  Squirrel: { Component: Squirrel, tags: ["Animal", "Save"] },
  Stamp: { Component: Stamp, tags: ["Crafts", "Approve"] },
  Star: { Component: Star, tags: ["Shapes", "Favorite", "Sky", "Astronomy"] },
  Stethoscope: {
    Component: Stethoscope,
    tags: ["Heartbeat", "Health", "Medicine"],
  },
  Store: { Component: Store, tags: ["Shop"] },
  Sun: { Component: Sun, tags: [] },
  SwatchBook: {
    Component: SwatchBook,
    tags: ["Paint", "Colors", "Fabric", "Crafts"],
  },
  Sword: { Component: Sword, tags: ["Weapon", "Blade"] },
  Syringe: { Component: Syringe, tags: ["Needle", "Medicine", "Prescription"] },
  Tablet: {
    Component: Tablet,
    tags: ["Computer", "Electronics", "Desktop", "Gear", "Gaming", "Devices"],
  },
  Tag: { Component: Tag, tags: ["Category", "Discount", "Shopping"] },
  Target: { Component: Target, tags: ["Bullseye", "Aim"] },
  Telescope: {
    Component: Telescope,
    tags: ["Stars", "Sky", "Galaxy", "Moon", "Science", "Astronomy"],
  },
  Tent: { Component: Tent, tags: ["Camping", "Gear", "Equipment", "Outdoors"] },
  Theater: {
    Component: Theater,
    tags: ["Stage", "Play", "Movies", "Broadway", "Entertainment"],
  },
  Thermometer: {
    Component: Thermometer,
    tags: ["Health", "Fever", "Temperature"],
  },
  Yarn: {
    Component: Thread,
    Tags: ["Crafts", "Sewing", "Yarn", "Spool"],
  },
  Trailer: {
    Component: Trailer,
    tags: ["Caravan", "Transportation", "Camping", "Travel", "Winnebago"],
  },
  Train: {
    Component: Tram,
    tags: ["Subway", "Transportation", "Tram", "Transit", "Travel", "Commute"],
  },
  Lego: { Component: ToyBrick, tags: ["Block", "Brick", "Toys", "Build"] },
  Tractor: { Component: Tractor, tags: ["Farm", "Equipment", "Power tools"] },
  Trash: {
    Component: Trash,
    tags: ["Garbage", "Can", "Waste", "Delete", "Erase"],
  },
  Trash2: {
    Component: Trash2,
    tags: ["Garbage", "Can", "Waste", "Delete", "Erase"],
  },
  Trees: { Component: Trees, tags: ["Woods", "Outdoors", "Nature"] },
  Triangle: { Component: Triangle, tags: ["Shapes"] },
  Trophy: { Component: Trophy, tags: ["Winner", "Award"] },
  Truck: {
    Component: Truck,
    tags: [
      "Haul",
      "Vehicle",
      "Travel",
      "Van",
      "Cargo",
      "Semi",
      "Tractor",
      "Trailer",
    ],
  },
  Turntable: { Component: Turntable, tags: ["Record player", "DJ", "Music"] },
  Turtle: { Component: Turtle, tags: ["Animal", "Shell", "Slow", "Tortoise"] },
  Tv: {
    Component: Tv,
    tags: ["Electronics", "Entertainment", "Video", "Movies", "Watch"],
  },
  Umbrella: { Component: Umbrella, tags: ["Rain", "Protection"] },
  User: { Component: User, tags: ["Person"] },
  People: { Component: Users, tags: ["Family", "Person", "Users", "Humans"] },
  Utensils: {
    Component: Utensils,
    tags: [
      "Food",
      "Kitchen",
      "Cutlery",
      "Fork",
      "Spoon",
      "Knife",
      "Eating",
      "Silverware",
      "Dishes",
    ],
  },
  UtensilsCrossed: {
    Component: UtensilsCrossed,
    tags: [
      "Food",
      "Kitchen",
      "Cutlery",
      "Fork",
      "Spoon",
      "Knife",
      "Eating",
      "Silverware",
      "Dishes",
    ],
  },
  Vault: { Component: Vault, tags: ["Bank", "Security", "Lockbox", "Money"] },
  Video: {
    Component: Video,
    tags: ["Tape", "Movie", "Watch", "Entertainment", "Television", "TV"],
  },
  Videotape: {
    Component: Videotape,
    tags: [
      "VHS",
      "Movie",
      "Recording",
      "Entertainment",
      "Media",
      "Watch",
      "TIVO",
      "DVR",
    ],
  },
  Volleyball: {
    Component: Volleyball,
    tags: ["Sports", "Athletics"],
  },
  Wallet: {
    Component: Wallet,
    tags: ["Money", "Credit", "Payment", "Cash", "Finances"],
  },
  WalletCards: {
    Component: WalletCards,
    tags: ["Money", "Credit", "Payment", "Finances"],
  },
  WandSparkles: { Component: WandSparkles, tags: ["Magic wand", "Tada"] },
  Warehouse: {
    Component: Warehouse,
    tags: ["Building", "Storage", "Depot", "Merchandise"],
  },
  WashingMachine: {
    Component: WashingMachine,
    tags: ["Clean", "Appliance", "Laundry", "Drier", "Dryer"],
  },
  Watch: { Component: Watch, tags: ["Wrist", "Time", "Clock"] },
  WavesLadder: {
    Component: WavesLadder,
    tags: ["Pool", "Swimming", "Aquatic", "Exercise", "Home"],
  },
  Webcam: { Component: Webcam, tags: ["Electronics", "Video", "Stream"] },
  Wifi: {
    Component: Wifi,
    tags: ["Netword", "Router", "Signal", "Internet", "Connection"],
  },
  Wine: { Component: Wine, tags: ["Drinks", "Kitchen", "Alcohol", "Liquor"] },
  WineBottle: {
    Component: WineBottle,
    tags: ["Drinks", "Kitchen", "Alcohol", "Liquor"],
  },
  Wrench: { Component: Wrench, tags: ["Tools", "Fix", "Repair"] },
};
