import {
  Activity,
  AlarmCheck,
  Album,
  AlertCircle,
  AlertTriangle,
  Anvil,
  Aperture,
  Archive,
  ArchiveRestore,
  ArrowBigDown,
  ArrowBigLeft,
  ArrowBigRight,
  ArrowBigUp,
  ArrowDownCircle,
  ArrowLeftCircle,
  ArrowRightCircle,
  ArrowUpCircle,
  AtSign,
  Award,
  Axe,
  Baby,
  Backpack,
  BadgeCheck,
  Ban,
  Banknote,
  Battery,
  BatteryCharging,
  BatteryFull,
  BatteryLow,
  Beaker,
  Bed,
  Bell,
  BellRing,
  Bike,
  Binoculars,
  Bird,
  Blocks,
  Bone,
  Book,
  BookImage,
  Bookmark,
  BookmarkMinus,
  BookmarkPlus,
  BookOpen,
  BoomBox,
  Box,
  Boxes,
  Briefcase,
  BriefcaseBusiness,
  Brush,
  Bug,
  Building,
  Cable,
  Cake,
  Calculator,
  Calendar,
  CalendarCheck,
  CalendarPlus,
  Camera,
  Car,
  CassetteTape,
  Cast,
  Cctv,
  CheckCircle,
  CheckSquare,
  CheckSquare2,
  ChefHat,
  Circle,
  Clipboard,
  ClipboardList,
  Clock,
  Cloud,
  CloudDrizzle,
  CloudLightning,
  CloudRain,
  CloudSnow,
  Coffee,
  Coins,
  Computer,
  Container,
  CookingPot,
  Copy,
  Cpu,
  CreditCard,
  Cross,
  Crosshair,
  Cuboid,
  Cylinder,
  Delete,
  DiamondMinus,
  DiamondPlus,
  Dice1,
  Dice2,
  Dice3,
  Dice4,
  Dice5,
  Dice6,
  Disc,
  Disc2,
  DivideSquare,
  Dog,
  DollarSign,
  DownloadCloud,
  Dribbble as Basketball,
  Drill,
  Droplet,
  Drum,
  Ear,
  Edit,
  Edit2 as Pen,
  Egg,
  Eye,
  Feather,
  Fence,
  File,
  FileImage,
  Film,
  Filter,
  Fingerprint,
  FireExtinguisher,
  Fish,
  Flag,
  Flame,
  FlagTriangleRight,
  Flashlight,
  FlaskRound as Flask,
  Flower,
  Flower2,
  Folder,
  FolderLock,
  FolderOpen,
  Folders,
  FolderUp,
  Frown,
  Fuel,
  Gamepad2,
  Gavel,
  Gem,
  Ghost,
  Gift,
  Glasses,
  Globe,
  Grab,
  GraduationCap,
  Grid,
  Hammer,
  Hand,
  HandMetal,
  HardDrive,
  HardHat,
  Headphones,
  Heart,
  HeartCrack as BrokenHeart,
  HeartPlus,
  HeartPulse,
  HelpCircle,
  Hexagon,
  Highlighter,
  Home,
  Image,
  Inbox,
  Info,
  Joystick,
  Key,
  KeyRound,
  Keyboard,
  Lamp,
  LampFloor,
  Landmark,
  Laptop,
  Layers,
  Leaf,
  LeafyGreen,
  Library,
  LibraryBig,
  LifeBuoy,
  Lightbulb,
  Lock,
  LockOpen,
  Luggage,
  Magnet,
  Mail,
  Mailbox,
  MailOpen,
  Map,
  MapPin,
  Megaphone,
  MemoryStick,
  MessageCircle,
  MessageSquare,
  Mic,
  Mic2,
  Microscope,
  Microwave,
  MinusCircle,
  MinusSquare,
  Monitor,
  Moon,
  MoonStar,
  Mouse,
  Music,
  Music2,
  Navigation,
  Navigation2,
  Network,
  Notebook,
  NotebookPen,
  NotebookTabs,
  Octagon,
  Origami,
  Package,
  Package2,
  PackageOpen,
  PackagePlus,
  Paintbrush,
  PaintBucket,
  PaintRoller,
  Palette,
  Paperclip,
  Pause,
  PauseCircle,
  PencilRuler,
  PenTool,
  Phone,
  PhoneCall,
  Piano,
  PieChart,
  PiggyBank,
  Pill,
  PillBottle,
  Pin,
  Plane,
  Play,
  PlayCircle,
  Plug,
  PlusCircle,
  PlusSquare,
  Pocket,
  PocketKnife,
  Presentation,
  Printer,
  Projector,
  Puzzle,
  Pyramid,
  QrCode,
  Radar,
  Radiation,
  Radio,
  RadioTower,
  Rainbow,
  Receipt,
  RectangleGoggles,
  RectangleVertical,
  RectangleHorizontal,
  Refrigerator,
  Ribbon,
  Rocket,
  RockingChair,
  Route,
  Router,
  Ruler,
  RulerDimensionLine,
  Sailboat,
  Save,
  School,
  Scissors,
  Search,
  Send,
  SendHorizontal,
  Server,
  Settings,
  Shell,
  Shield,
  ShieldCheck,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Shovel,
  ShowerHead,
  Shredder,
  SignpostBig,
  Slice,
  Smartphone,
  SmartphoneCharging,
  Smile,
  Sofa,
  Speaker,
  SprayCan,
  Sprout,
  Square,
  SquareScissors,
  SquareLibrary,
  Squirrel,
  Stamp,
  Star,
  Stethoscope,
  StopCircle,
  Store,
  Sun,
  SunDim,
  SunMoon,
  Sunrise,
  Sunset,
  SwatchBook,
  Sword,
  Syringe,
  Tablet,
  TabletSmartphone,
  Tag,
  Target,
  Telescope,
  Tent,
  Theater,
  Thermometer,
  ThumbsDown,
  ThumbsUp,
  Tornado,
  ToyBrick,
  Tractor,
  Trash,
  Trash2,
  TreePalm as PalmTree,
  TreePine as PineTree,
  Trees,
  Triangle,
  Trophy,
  Truck,
  Turtle,
  Tv,
  Umbrella,
  Unlock,
  User,
  UserCircle,
  Users,
  Utensils,
  UtilityPole,
  Vault,
  Video,
  Videotape,
  Volleyball,
  Wallet,
  WalletCards,
  WalletMinimal,
  WandSparkles,
  Warehouse,
  WashingMachine,
  Watch,
  Waves,
  WavesLadder,
  Webcam,
  Wifi,
  Wind,
  Wine,
  Wrench,
  XCircle,
  XSquare,
  Zap as Lightning,
  Armchair,
  Blinds,
  BrushCleaning,
} from "lucide-react";

import { Spool } from "@/app/assets/Spool";
import { PinCushion } from "@/app/assets/PinCushion";

export const lucideIconList = {
  Activity: {
    Component: Activity,
    tags: ["Heartbeat", "Pulse", "Health", "Test"],
  },
  AlarmCheck: {
    Component: AlarmCheck,
    tags: ["Clock", "Reminder", "Stopwatch", "Time", "Todo"],
  },
  Album: { Component: Album, tags: ["Pictures", "Photos", "Memories"] },
  AlertCircle: { Component: AlertCircle, tags: [] },
  AlertTriangle: { Component: AlertTriangle, tags: [] },
  Anvil: { Component: Anvil, tags: [] },
  Aperture: { Component: Aperture, tags: [] },
  Archive: { Component: Archive, tags: [] },
  ArchiveRestore: { Component: ArchiveRestore, tags: [] },
  Armchair: {
    Component: Armchair,
    tags: [
      "Sofa",
      "Loveseat",
      "Chair",
      "Furniture",
      "Living room",
      "Den",
      "Home",
      "Couch",
      "Rest",
    ],
  },
  ArrowBigDown: { Component: ArrowBigDown, tags: [] },
  ArrowBigLeft: { Component: ArrowBigLeft, tags: [] },
  ArrowBigRight: { Component: ArrowBigRight, tags: [] },
  ArrowBigUp: { Component: ArrowBigUp, tags: [] },
  ArrowDownCircle: { Component: ArrowDownCircle, tags: [] },
  ArrowLeftCircle: { Component: ArrowLeftCircle, tags: [] },
  ArrowRightCircle: { Component: ArrowRightCircle, tags: [] },
  ArrowUpCircle: { Component: ArrowUpCircle, tags: [] },
  AtSign: { Component: AtSign, tags: [] },
  Award: { Component: Award, tags: [] },
  Axe: { Component: Axe, tags: [] },
  Baby: { Component: Baby, tags: ["Child", "Infant", "Kid", "Family"] },
  Backpack: { Component: Backpack, tags: [] },
  BadgeCheck: { Component: BadgeCheck, tags: [] },
  Ban: { Component: Ban, tags: [] },
  Banknote: { Component: Banknote, tags: [] },
  Basketball: {
    Component: Basketball,
    tags: ["Sports", "Sporting goods", "Equipment"],
  },
  Battery: { Component: Battery, tags: [] },
  BatteryCharging: { Component: BatteryCharging, tags: [] },
  BatteryFull: { Component: BatteryFull, tags: [] },
  BatteryLow: { Component: BatteryLow, tags: [] },
  Beaker: { Component: Beaker, tags: [] },
  Bed: { Component: Bed, tags: ["Sleep", "Home", "Room", "Rest", "Furniture"] },
  Bell: { Component: Bell, tags: [] },
  BellRing: { Component: BellRing, tags: [] },
  Bike: { Component: Bike, tags: [] },
  Binoculars: { Component: Binoculars, tags: [] },
  Bird: { Component: Bird, tags: [] },
  Blinds: {
    Component: Blinds,
    tags: ["Curtains", "Home", "Shade", "Window", "Decor"],
  },
  Blocks: { Component: Blocks, tags: [] },
  Bone: { Component: Bone, tags: [] },
  Book: { Component: Book, tags: [] },
  BookImage: { Component: BookImage, tags: [] },
  Bookmark: { Component: Bookmark, tags: [] },
  BookmarkMinus: { Component: BookmarkMinus, tags: [] },
  BookmarkPlus: { Component: BookmarkPlus, tags: [] },
  BookOpen: { Component: BookOpen, tags: [] },
  BoomBox: { Component: BoomBox, tags: [] },
  Box: { Component: Box, tags: ["Container", "Storage"] },
  Boxes: { Component: Boxes, tags: ["Containers", "Storage"] },
  Briefcase: { Component: Briefcase, tags: [] },
  BriefcaseBusiness: { Component: BriefcaseBusiness, tags: [] },
  BrokenHeart: { Component: BrokenHeart, tags: [] },
  Brush: { Component: Brush, tags: ["Paint", "Color"] },
  BrushCleaning: {
    Component: BrushCleaning,
    tags: ["Sweep", "Broom", "Clean", "Dirt", "Mop", "Floor"],
  },
  Bug: { Component: Bug, tags: ["Insect", "Pest"] },
  Building: { Component: Building, tags: [] },
  Cable: { Component: Cable, tags: [] },
  Cake: { Component: Cake, tags: [] },
  Calculator: { Component: Calculator, tags: [] },
  Calendar: { Component: Calendar, tags: [] },
  CalendarCheck: { Component: CalendarCheck, tags: [] },
  CalendarPlus: { Component: CalendarPlus, tags: [] },
  Camera: {
    Component: Camera,
    tags: ["Photography", "Pictures", "Lens", "Capture"],
  },
  Car: { Component: Car, tags: ["Vehicle", "Travel", "Transportation", "SUV"] },
  CassetteTape: {
    Component: CassetteTape,
    tags: ["Retro", "Music", "Sound", "Tape", "Recording"],
  },
  Cast: { Component: Cast, tags: [] },
  Cctv: { Component: Cctv, tags: [] },
  CheckCircle: { Component: CheckCircle, tags: [] },
  CheckSquare: { Component: CheckSquare, tags: [] },
  CheckSquare2: { Component: CheckSquare2, tags: [] },
  ChefHat: {
    Component: ChefHat,
    tags: ["Cooking", "Kitchen", "Restaurant", "Dining"],
  },
  Circle: { Component: Circle, tags: [] },
  Clipboard: { Component: Clipboard, tags: [] },
  ClipboardList: { Component: ClipboardList, tags: [] },
  Clock: { Component: Clock, tags: [] },
  Cloud: { Component: Cloud, tags: ["Weather", "Sky"] },
  CloudDrizzle: {
    Component: CloudDrizzle,
    tags: ["Rain", "Weather", "Wet", "Sky"],
  },
  CloudLightning: { Component: CloudLightning, tags: [] },
  CloudRain: { Component: CloudRain, tags: [] },
  CloudSnow: { Component: CloudSnow, tags: [] },
  Coffee: { Component: Coffee, tags: [] },
  Coins: { Component: Coins, tags: [] },
  Computer: { Component: Computer, tags: [] },
  Container: { Component: Container, tags: [] },
  CookingPot: { Component: CookingPot, tags: ["Pans", "Kitchen", "Food"] },
  Copy: { Component: Copy, tags: [] },
  Cpu: { Component: Cpu, tags: [] },
  CreditCard: { Component: CreditCard, tags: ["Plastic", "Payment", "Money"] },
  Cross: { Component: Cross, tags: [] },
  Crosshair: { Component: Crosshair, tags: [] },
  Cuboid: { Component: Cuboid, tags: [] },
  Cylinder: { Component: Cylinder, tags: [] },
  Delete: { Component: Delete, tags: [] },
  DiamondMinus: { Component: DiamondMinus, tags: [] },
  DiamondPlus: { Component: DiamondPlus, tags: [] },
  Dice1: { Component: Dice1, tags: [] },
  Dice2: { Component: Dice2, tags: [] },
  Dice3: { Component: Dice3, tags: [] },
  Dice4: { Component: Dice4, tags: [] },
  Dice5: { Component: Dice5, tags: [] },
  Dice6: { Component: Dice6, tags: [] },
  Disc: { Component: Disc, tags: [] },
  Disc2: { Component: Disc2, tags: [] },
  DivideSquare: { Component: DivideSquare, tags: [] },
  Dog: { Component: Dog, tags: ["Pet", "Animal", "Family"] },
  DollarSign: {
    Component: DollarSign,
    tags: ["Money", "Finances", "Cash", "Savings"],
  },
  DownloadCloud: { Component: DownloadCloud, tags: [] },
  Drill: { Component: Drill, tags: ["Tools", "Home", "Wood", "Hole"] },
  Droplet: { Component: Droplet, tags: [] },
  Drum: { Component: Drum, tags: [] },
  Ear: { Component: Ear, tags: ["Hearing", "Sound"] },
  Edit: { Component: Edit, tags: [] },
  Egg: { Component: Egg, tags: [] },
  Eye: { Component: Eye, tags: [] },
  Feather: { Component: Feather, tags: [] },
  Fence: { Component: Fence, tags: [] },
  File: { Component: File, tags: [] },
  FileImage: { Component: FileImage, tags: [] },
  Film: { Component: Film, tags: [] },
  Filter: { Component: Filter, tags: [] },
  Fingerprint: { Component: Fingerprint, tags: [] },
  FireExtinguisher: { Component: FireExtinguisher, tags: [] },
  Fish: { Component: Fish, tags: [] },
  Flag: { Component: Flag, tags: [] },
  Flame: { Component: Flame, tags: [] },
  FlagTriangleRight: { Component: FlagTriangleRight, tags: [] },
  Flashlight: { Component: Flashlight, tags: [] },
  Flask: { Component: Flask, tags: [] },
  Flower: { Component: Flower, tags: [] },
  Flower2: { Component: Flower2, tags: [] },
  Folder: { Component: Folder, tags: [] },
  FolderLock: { Component: FolderLock, tags: [] },
  FolderOpen: { Component: FolderOpen, tags: [] },
  Folders: { Component: Folders, tags: [] },
  FolderUp: { Component: FolderUp, tags: [] },
  Frown: { Component: Frown, tags: [] },
  Fuel: { Component: Fuel, tags: ["Power", "Oil", "Gasoline", "Pump"] },
  Gamepad2: {
    Component: Gamepad2,
    tags: [
      "Gaming",
      "Play",
      "Entertainment",
      "Joystick",
      "Playstation",
      "Nintendo",
      "XBox",
      "RPG",
    ],
  },
  Gavel: { Component: Gavel, tags: [] },
  Gem: {
    Component: Gem,
    tags: [
      "Diamond",
      "Jewelry",
      "Crafts",
      "Ring",
      "Valuables",
      "Expensive",
      "Ruby",
      "Emerald",
    ],
  },
  Ghost: { Component: Ghost, tags: [] },
  Gift: { Component: Gift, tags: ["Present", "Bow", "Christmas"] },
  Glasses: { Component: Glasses, tags: ["Vision", "Eyes", "Sight"] },
  Globe: { Component: Globe, tags: [] },
  Grab: { Component: Grab, tags: [] },
  GraduationCap: {
    Component: GraduationCap,
    tags: ["School", "College", "University", "Education", "Diploma"],
  },
  Grid: { Component: Grid, tags: [] },
  Hammer: { Component: Hammer, tags: [] },
  Hand: { Component: Hand, tags: [] },
  HandMetal: { Component: HandMetal, tags: [] },
  HardDrive: { Component: HardDrive, tags: [] },
  HardHat: {
    Component: HardHat,
    tags: ["Construction", "Build", "Make", "Safety", "Protection", "Headgear"],
  },
  Headphones: {
    Component: Headphones,
    tags: ["Music", "Earphones", "Play", "Sound", "Hearing"],
  },
  Heart: {
    Component: Heart,
    tags: ["Health", "Love", "Favorite", "Affection"],
  },
  HeartPlus: {
    Component: HeartPlus,
    tags: ["Health", "Activity", "Beat", "Testing"],
  },
  HeartPulse: {
    Component: HeartPulse,
    tags: ["Health", "Activity", "Beat", "Testing"],
  },
  HelpCircle: { Component: HelpCircle, tags: [] },
  Hexagon: { Component: Hexagon, tags: [] },
  Highlighter: {
    Component: Highlighter,
    tags: ["Neon", "Drawing", "Color", "Crafts"],
  },
  Home: { Component: Home, tags: [] },
  Image: { Component: Image, tags: [] },
  Inbox: { Component: Inbox, tags: [] },
  Info: { Component: Info, tags: [] },
  Joystick: { Component: Joystick, tags: ["Game", "Play", "Electronics"] },
  Key: { Component: Key, tags: ["Security", "Safety", "Door", "Home"] },
  KeyRound: {
    Component: KeyRound,
    tags: ["Security", "Safety", "Door", "Home"],
  },
  Keyboard: { Component: Keyboard, tags: [] },
  Lamp: { Component: Lamp, tags: ["Light", "Bulb", "Home", "Decor"] },
  LampFloor: { Component: LampFloor, tags: ["Light", "Bulb", "Home", "Decor"] },
  Landmark: { Component: Landmark, tags: [] },
  Laptop: {
    Component: Laptop,
    tags: ["Computer", "Electronics", "Desktop", "Gear", "Gaming"],
  },
  Layers: { Component: Layers, tags: [] },
  Leaf: { Component: Leaf, tags: [] },
  LeafyGreen: { Component: LeafyGreen, tags: [] },
  Library: { Component: Library, tags: ["Books", "Reading", "Collection"] },
  LibraryBig: {
    Component: LibraryBig,
    tags: ["Books", "Reading", "Collection"],
  },
  LifeBuoy: {
    Component: LifeBuoy,
    tags: ["Water", "Rescue", "Safety", "Flotation", "Floatation"],
  },
  Lightbulb: { Component: Lightbulb, tags: ["Idea", "Light", "Home"] },
  Lightning: { Component: Lightning, tags: [] },
  Lock: { Component: Lock, tags: ["Security", "Key", "Safety"] },
  LockOpen: { Component: LockOpen, tags: ["Security", "Safety", "Key"] },
  Luggage: {
    Component: Luggage,
    tags: ["Travel", "Storage", "Clothes", "Bags"],
  },
  Magnet: { Component: Magnet, tags: [] },
  Mail: { Component: Mail, tags: [] },
  Mailbox: { Component: Mailbox, tags: [] },
  MailOpen: { Component: MailOpen, tags: [] },
  Map: { Component: Map, tags: [] },
  MapPin: { Component: MapPin, tags: [] },
  Megaphone: { Component: Megaphone, tags: [] },
  MemoryStick: { Component: MemoryStick, tags: [] },
  MessageCircle: { Component: MessageCircle, tags: [] },
  MessageSquare: { Component: MessageSquare, tags: [] },
  Mic: {
    Component: Mic,
    tags: ["Podcast", "Sound", "Radio", "Electronics", "Recording"],
  },
  Mic2: {
    Component: Mic2,
    tags: ["Podcast", "Sound", "Radio", "Electronics", "Recording"],
  },
  Microscope: { Component: Microscope, tags: ["Science", "Magnify", "Slides"] },
  Microwave: {
    Component: Microwave,
    tags: ["Kitchen", "Appliances", "Cook", "Nuke", "Food"],
  },
  MinusCircle: { Component: MinusCircle, tags: [] },
  MinusSquare: { Component: MinusSquare, tags: [] },
  Monitor: {
    Component: Monitor,
    tags: ["Computer", "Electronics", "Devices", "Accessories", "Peripherals"],
  },
  Moon: { Component: Moon, tags: ["Sky", "Night"] },
  MoonStar: { Component: MoonStar, tags: ["Sky", "Night"] },
  Mouse: {
    Component: Mouse,
    tags: ["Computer", "Electronics", "Devices", "Accessories", "Peripherals"],
  },
  Music: { Component: Music, tags: ["Note", "Sheet", "Sound", "Instruments"] },
  Music2: {
    Component: Music2,
    tags: ["Note", "Sheet", "Sound", "Instruments"],
  },
  Navigation: {
    Component: Navigation,
    tags: ["GPS", "Route", "Directions", "Location"],
  },
  Navigation2: {
    Component: Navigation2,
    tags: ["GPS", "Route", "Directions", "Location"],
  },
  Network: { Component: Network, tags: [] },
  Notebook: { Component: Notebook, tags: [] },
  NotebookPen: { Component: NotebookPen, tags: [] },
  NotebookTabs: { Component: NotebookTabs, tags: [] },
  Octagon: { Component: Octagon, tags: [] },
  Origami: { Component: Origami, tags: [] },
  Package: { Component: Package, tags: [] },
  Package2: { Component: Package2, tags: [] },
  PackageOpen: { Component: PackageOpen, tags: [] },
  PackagePlus: { Component: PackagePlus, tags: [] },
  Paintbrush: {
    Component: Paintbrush,
    tags: ["Brush", "Color", "Home", "Decor"],
  },
  PaintBucket: {
    Component: PaintBucket,
    tags: ["Brush", "Color", "Home", "Decor"],
  },
  PaintRoller: {
    Component: PaintRoller,
    tags: ["Brush", "Color", "Home", "Decor"],
  },
  Palette: { Component: Palette, tags: ["Brush", "Color", "Home", "Decor"] },
  PalmTree: { Component: PalmTree, tags: [] },
  Paperclip: { Component: Paperclip, tags: ["Attach", "Staple"] },
  Pause: { Component: Pause, tags: [] },
  PauseCircle: { Component: PauseCircle, tags: [] },
  Pen: { Component: Pen, tags: [] },
  PencilRuler: { Component: PencilRuler, tags: [] },
  PenTool: { Component: PenTool, tags: [] },
  Phone: { Component: Phone, tags: [] },
  PhoneCall: { Component: PhoneCall, tags: [] },
  Piano: {
    Component: Piano,
    tags: ["Music", "Instruments", "Keyboard", "Sound"],
  },
  PieChart: { Component: PieChart, tags: [] },
  PiggyBank: {
    Component: PiggyBank,
    tags: ["Money", "Finance", "Savings", "Cash"],
  },
  Pill: {
    Component: Pill,
    tags: [
      "Medicine",
      "Medication",
      "Pain",
      "Prescription",
      "Headache",
      "Sore",
    ],
  },
  PillBottle: {
    Component: PillBottle,
    tags: [
      "Medicine",
      "Medication",
      "Pain",
      "Prescription",
      "Headache",
      "Sore",
    ],
  },
  Pin: { Component: Pin, tags: [] },
  PinCushion: { Component: PinCushion, tags: ["Sewing", "Needles", "Crafts"] },
  PineTree: { Component: PineTree, tags: [] },
  Plane: {
    Component: Plane,
    tags: ["Jet", "Travel", "Air", "Aero", "Aviation", "Machines", "Flight"],
  },
  Play: { Component: Play, tags: [] },
  PlayCircle: { Component: PlayCircle, tags: [] },
  Plug: { Component: Plug, tags: ["Electronics", "Power"] },
  PlusCircle: { Component: PlusCircle, tags: [] },
  PlusSquare: { Component: PlusSquare, tags: [] },
  Pocket: { Component: Pocket, tags: [] },
  PocketKnife: {
    Component: PocketKnife,
    tags: ["Cut", "Blade", "EDC", "Tools"],
  },
  Presentation: { Component: Presentation, tags: [] },
  Printer: {
    Component: Printer,
    tags: [
      "Devices",
      "Paper",
      "Accessories",
      "Computer",
      "Electronics",
      "Device",
    ],
  },
  Projector: {
    Component: Projector,
    tags: ["Entertainment", "Movies", "TV", "Home", "Watch"],
  },
  Puzzle: { Component: Puzzle, tags: ["Piece", "Toy", "Games", "Jigsaw"] },
  Pyramid: { Component: Pyramid, tags: [] },
  QrCode: { Component: QrCode, tags: [] },
  Radar: { Component: Radar, tags: [] },
  Radiation: { Component: Radiation, tags: [] },
  Radio: { Component: Radio, tags: [] },
  RadioTower: { Component: RadioTower, tags: [] },
  Rainbow: { Component: Rainbow, tags: [] },
  Receipt: {
    Component: Receipt,
    tags: ["Purchase", "Payment", "Record", "Money"],
  },
  RectangleGoggles: {
    Component: RectangleGoggles,
    tags: ["Eye protection", "Ski", "Face"],
  },
  RectangleVertical: { Component: RectangleVertical, tags: [] },
  RectangleHorizontal: { Component: RectangleHorizontal, tags: [] },
  Refrigerator: {
    Component: Refrigerator,
    tags: ["Fridge", "Food", "Cold", "Cool", "Kitchen", "Home", "Appliances"],
  },
  Ribbon: { Component: Ribbon, tags: ["Gift", "Award"] },
  Rocket: {
    Component: Rocket,
    tags: ["Launch", "Space", "Sky", "Aerospace", "Flight"],
  },
  RockingChair: { Component: RockingChair, tags: ["Furniture", "Home"] },
  Route: { Component: Route, tags: [] },
  Router: { Component: Router, tags: [] },
  Ruler: { Component: Ruler, tags: ["Measure", "Crafts", "Tools"] },
  RulerDimensionLine: {
    Component: RulerDimensionLine,
    tags: ["Measure", "Crafts", "Tools"],
  },
  Sailboat: { Component: Sailboat, tags: [] },
  Save: { Component: Save, tags: [] },
  School: { Component: School, tags: ["Education", "Class", "Learning"] },
  Scissors: {
    Component: Scissors,
    tags: ["Cut", "Sewing", "Crafting", "Tools"],
  },
  Search: { Component: Search, tags: [] },
  Send: { Component: Send, tags: [] },
  SendHorizontal: { Component: SendHorizontal, tags: [] },
  Server: { Component: Server, tags: [] },
  Settings: { Component: Settings, tags: [] },
  Shell: { Component: Shell, tags: [] },
  Shield: { Component: Shield, tags: [] },
  ShieldCheck: { Component: ShieldCheck, tags: [] },
  Shirt: {
    Component: Shirt,
    tags: ["Clothes", "Apparel", "Home", "Wear", "Fashion"],
  },
  ShoppingBag: { Component: ShoppingBag, tags: [] },
  ShoppingCart: { Component: ShoppingCart, tags: [] },
  Shovel: { Component: Shovel, tags: [] },
  ShowerHead: { Component: ShowerHead, tags: [] },
  Shredder: { Component: Shredder, tags: [] },
  SignpostBig: { Component: SignpostBig, tags: [] },
  Slice: { Component: Slice, tags: [] },
  Smartphone: { Component: Smartphone, tags: [] },
  SmartphoneCharging: { Component: SmartphoneCharging, tags: [] },
  Smile: { Component: Smile, tags: ["Happy", "Face"] },
  Sofa: {
    Component: Sofa,
    tags: ["Couch", "Home", "Chair", "Rest", "Living room", "Den", "Loveseat"],
  },
  Speaker: {
    Component: Speaker,
    tags: ["Sound", "Music", "Electronics", "Home", "Entertainment"],
  },
  Spool: { Component: Spool, tags: ["Sewing", "Thread", "Yarn", "Crafts"] },
  SprayCan: {
    Component: SprayCan,
    tags: ["Paint", "Graffiti", "Tagging", "Color"],
  },
  Sprout: { Component: Sprout, tags: [] },
  Square: { Component: Square, tags: [] },
  SquareScissors: { Component: SquareScissors, tags: [] },
  SquareLibrary: { Component: SquareLibrary, tags: [] },
  Squirrel: { Component: Squirrel, tags: [] },
  Stamp: { Component: Stamp, tags: [] },
  Star: { Component: Star, tags: [] },
  Stethoscope: {
    Component: Stethoscope,
    tags: ["Heartbeat", "Health", "Medicine"],
  },
  StopCircle: { Component: StopCircle, tags: [] },
  Store: { Component: Store, tags: [] },
  Sun: { Component: Sun, tags: [] },
  SunDim: { Component: SunDim, tags: [] },
  SunMoon: { Component: SunMoon, tags: [] },
  Sunrise: { Component: Sunrise, tags: [] },
  Sunset: { Component: Sunset, tags: [] },
  SwatchBook: {
    Component: SwatchBook,
    tags: ["Paint", "Colors", "Wall", "Fabric"],
  },
  Sword: { Component: Sword, tags: ["Weapon", "Blade"] },
  Syringe: { Component: Syringe, tags: ["Needle", "Medicine", "Prescription"] },
  Tablet: {
    Component: Tablet,
    tags: ["Computer", "Electronics", "Desktop", "Gear", "Gaming", "Devices"],
  },
  TabletSmartphone: {
    Component: TabletSmartphone,
    tags: ["Computer", "Electronics", "Desktop", "Gear", "Gaming", "Devices"],
  },
  Tag: { Component: Tag, tags: ["Category", "Discount", "Shopping"] },
  Target: { Component: Target, tags: ["Bullseye", "Aim"] },
  Telescope: { Component: Telescope, tags: ["Stars", "Sky", "Galaxy", "Moon"] },
  Tent: { Component: Tent, tags: ["Camping", "Gear", "Equipment", "Outdoors"] },
  Theater: {
    Component: Theater,
    tags: ["Stage", "Play", "Movies", "Broadway", "Entertainment"],
  },
  Thermometer: {
    Component: Thermometer,
    tags: ["Health", "Fever", "Temperature"],
  },
  ThumbsDown: { Component: ThumbsDown, tags: [] },
  ThumbsUp: { Component: ThumbsUp, tags: [] },
  Tornado: {
    Component: Tornado,
    tags: ["Wind", "Storm", "Weather", "Funnel", "Cyclone"],
  },
  ToyBrick: { Component: ToyBrick, tags: ["Legos"] },
  Tractor: { Component: Tractor, tags: ["Farm", "Equipment", "Power tools"] },
  Trash: { Component: Trash, tags: [] },
  Trash2: { Component: Trash2, tags: [] },
  Trees: { Component: Trees, tags: [] },
  Triangle: { Component: Triangle, tags: [] },
  Trophy: { Component: Trophy, tags: ["Winner", "Award"] },
  Truck: { Component: Truck, tags: [] },
  Turtle: { Component: Turtle, tags: [] },
  Tv: {
    Component: Tv,
    tags: ["Electronics", "Entertainment", "Video", "Movies", "Watch"],
  },
  Umbrella: { Component: Umbrella, tags: ["Rain", "Protection"] },
  Unlock: { Component: Unlock, tags: [] },
  User: { Component: User, tags: [] },
  UserCircle: { Component: UserCircle, tags: [] },
  Users: { Component: Users, tags: [] },
  Utensils: { Component: Utensils, tags: [] },
  UtilityPole: { Component: UtilityPole, tags: [] },
  Vault: { Component: Vault, tags: ["Bank", "Security", "Lockbox", "Money"] },
  Video: {
    Component: Video,
    tags: ["Tape", "Movie", "Watch", "Entertainment"],
  },
  Videotape: { Component: Videotape, tags: [] },
  Volleyball: { Component: Volleyball, tags: [] },
  Wallet: {
    Component: Wallet,
    tags: ["Money", "Credit", "Payment", "Cash", "Finances"],
  },
  WalletCards: {
    Component: WalletCards,
    tags: ["Money", "Credit", "Payment", "Finances"],
  },
  WalletMinimal: {
    Component: WalletMinimal,
    tags: ["Money", "Credit", "Payment", "Cash", "Finances"],
  },
  WandSparkles: { Component: WandSparkles, tags: ["Magic wand", "Tada"] },
  Warehouse: {
    Component: Warehouse,
    tags: ["Building", "Storage", "Depot", "Merchandise"],
  },
  WashingMachine: {
    Component: WashingMachine,
    tags: ["Clean", "Appliance", "Laundry", "Drier", "Dryer"],
  },
  Watch: { Component: Watch, tags: ["Wrist", "Time"] },
  Waves: { Component: Waves, tags: ["Water", "Beach", "Boat", "Sailing"] },
  WavesLadder: { Component: WavesLadder, tags: [] },
  Webcam: { Component: Webcam, tags: [] },
  Wifi: {
    Component: Wifi,
    tags: ["Netword", "Router", "Signal", "Internet", "Connection"],
  },
  Wind: { Component: Wind, tags: [] },
  Wine: { Component: Wine, tags: [] },
  Wrench: { Component: Wrench, tags: ["Tools", "Fix"] },
  XCircle: { Component: XCircle, tags: [] },
  XSquare: { Component: XSquare, tags: [] },
};

// export const lucideIconList = {
//   Activity,
//   AlarmCheck,
//   Album,
//   AlertCircle,
//   AlertTriangle,
//   Anvil,
//   Aperture,
//   Archive,
//   ArchiveRestore,
//   ArrowBigDown,
//   ArrowBigLeft,
//   ArrowBigRight,
//   ArrowBigUp,
//   ArrowDownCircle,
//   ArrowLeftCircle,
//   ArrowRightCircle,
//   ArrowUpCircle,
//   AtSign,
//   Award,
//   Axe,
//   Baby,
//   Backpack,
//   BadgeCheck,
//   Ban,
//   Banknote,
//   Basketball,
//   Battery,
//   BatteryCharging,
//   BatteryFull,
//   BatteryLow,
//   Beaker,
//   Bed,
//   Bell,
//   BellRing,
//   Bike,
//   Binoculars,
//   Bird,
//   Blocks,
//   Bone,
//   Book,
//   BookImage,
//   Bookmark,
//   BookmarkMinus,
//   BookmarkPlus,
//   BookOpen,
//   BoomBox,
//   Box,
//   Boxes,
//   Briefcase,
//   BriefcaseBusiness,
//   BrokenHeart,
//   Brush,
//   Bug,
//   Building,
//   Cable,
//   Cake,
//   Calculator,
//   Calendar,
//   CalendarCheck,
//   CalendarPlus,
//   Camera,
//   Car,
//   CassetteTape,
//   Cast,
//   Cctv,
//   CheckCircle,
//   CheckSquare,
//   CheckSquare2,
//   ChefHat,
//   Circle,
//   Clipboard,
//   ClipboardList,
//   Clock,
//   Cloud,
//   CloudDrizzle,
//   CloudLightning,
//   CloudRain,
//   CloudSnow,
//   Coffee,
//   Coins,
//   Computer,
//   Container,
//   CookingPot,
//   Copy,
//   Cpu,
//   CreditCard,
//   Cross,
//   Crosshair,
//   Cuboid,
//   Cylinder,
//   Delete,
//   DiamondMinus,
//   DiamondPlus,
//   Dice1,
//   Dice2,
//   Dice3,
//   Dice4,
//   Dice5,
//   Dice6,
//   Disc,
//   Disc2,
//   DivideSquare,
//   Dog,
//   DollarSign,
//   DownloadCloud,
//   Drill,
//   Droplet,
//   Drum,
//   Ear,
//   Edit,
//   Egg,
//   Eye,
//   Feather,
//   Fence,
//   File,
//   FileImage,
//   Film,
//   Filter,
//   Fingerprint,
//   FireExtinguisher,
//   Fish,
//   Flag,
//   Flame,
//   FlagTriangleRight,
//   Flashlight,
//   Flask,
//   Flower,
//   Flower2,
//   Folder,
//   FolderLock,
//   FolderOpen,
//   Folders,
//   FolderUp,
//   Frown,
//   Fuel,
//   Gamepad2,
//   Gavel,
//   Gem,
//   Ghost,
//   Gift,
//   Glasses,
//   Globe,
//   Grab,
//   GraduationCap,
//   Grid,
//   Hammer,
//   Hand,
//   HandMetal,
//   HardDrive,
//   HardHat,
//   Headphones,
//   Heart,
//   HeartPlus,
//   HeartPulse,
//   HelpCircle,
//   Hexagon,
//   Highlighter,
//   Home,
//   Image,
//   Inbox,
//   Info,
//   Joystick,
//   Key,
//   KeyRound,
//   Keyboard,
//   Lamp,
//   LampFloor,
//   Landmark,
//   Laptop,
//   Layers,
//   Leaf,
//   LeafyGreen,
//   Library,
//   LibraryBig,
//   LifeBuoy,
//   Lightbulb,
//   Lightning,
//   Lock,
//   LockOpen,
//   Luggage,
//   Luggage,
//   Magnet,
//   Mail,
//   Mailbox,
//   MailOpen,
//   Map,
//   MapPin,
//   Megaphone,
//   MemoryStick,
//   MessageCircle,
//   MessageSquare,
//   Mic,
//   Mic2,
//   Microscope,
//   Microwave,
//   MinusCircle,
//   MinusSquare,
//   Monitor,
//   Moon,
//   MoonStar,
//   Mouse,
//   Music,
//   Music2,
//   Navigation,
//   Navigation2,
//   Network,
//   Notebook,
//   NotebookPen,
//   NotebookTabs,
//   Octagon,
//   Origami,
//   Package,
//   Package2,
//   PackageOpen,
//   PackagePlus,
//   Paintbrush,
//   PaintBucket,
//   PaintRoller,
//   Palette,
//   PalmTree,
//   Paperclip,
//   Pause,
//   PauseCircle,
//   Pen,
//   PencilRuler,
//   PenTool,
//   Phone,
//   PhoneCall,
//   Piano,
//   PieChart,
//   PiggyBank,
//   Pill,
//   PillBottle,
//   Pin,
//   PineTree,
//   Plane,
//   Play,
//   PlayCircle,
//   Plug,
//   PlusCircle,
//   PlusSquare,
//   Pocket,
//   PocketKnife,
//   Presentation,
//   Printer,
//   Projector,
//   Puzzle,
//   Pyramid,
//   QrCode,
//   Radar,
//   Radiation,
//   Radio,
//   RadioTower,
//   Rainbow,
//   Receipt,
//   RectangleGoggles,
//   RectangleVertical,
//   RectangleHorizontal,
//   Refrigerator,
//   Ribbon,
//   Rocket,
//   RockingChair,
//   Route,
//   Router,
//   Ruler,
//   RulerDimensionLine,
//   Sailboat,
//   Save,
//   School,
//   Scissors,
//   Search,
//   Send,
//   SendHorizontal,
//   Server,
//   Settings,
//   Shell,
//   Shield,
//   ShieldCheck,
//   Shirt,
//   ShoppingBag,
//   ShoppingCart,
//   Shovel,
//   ShowerHead,
//   Shredder,
//   SignpostBig,
//   Slice,
//   Smartphone,
//   SmartphoneCharging,
//   Smile,
//   Speaker,
//   SprayCan,
//   Sprout,
//   Square,
//   SquareScissors,
//   SquareLibrary,
//   Squirrel,
//   Stamp,
//   Star,
//   Stethoscope,
//   StopCircle,
//   Store,
//   Sun,
//   SunDim,
//   SunMoon,
//   Sunrise,
//   Sunset,
//   SwatchBook,
//   Sword,
//   Syringe,
//   Tablet,
//   TabletSmartphone,
//   Tag,
//   Target,
//   Telescope,
//   Tent,
//   Theater,
//   Thermometer,
//   ThumbsDown,
//   ThumbsUp,
//   Tornado,
//   ToyBrick,
//   Tractor,
//   Trash,
//   Trash2,
//   Trees,
//   Triangle,
//   Trophy,
//   Truck,
//   Turtle,
//   Tv,
//   Umbrella,
//   Unlock,
//   User,
//   UserCircle,
//   Users,
//   Utensils,
//   UtilityPole,
//   Vault,
//   Video,
//   Videotape,
//   Volleyball,
//   Wallet,
//   WalletCards,
//   WalletMinimal,
//   WandSparkles,
//   Warehouse,
//   WashingMachine,
//   Watch,
//   Waves,
//   WavesLadder,
//   Webcam,
//   Wifi,
//   Wind,
//   Wine,
//   Wrench,
//   XCircle,
//   XSquare,
// };
